#CS231n Python Tutorial With Google Colab

This tutorial was originally written by [Justin Johnson](https://web.eecs.umich.edu/~justincj/) for cs231n. It was adapted as a Jupyter notebook for cs228 by [Volodymyr Kuleshov](http://web.stanford.edu/~kuleshov/) and [Isaac Caswell](https://symsys.stanford.edu/viewing/symsysaffiliate/21335).

This version has been adapted for Colab by Kevin Zakka for the Spring 2020 edition of [cs231n](https://cs231n.github.io/). It runs Python3 by default.

This version has been repurposed by Benjamín Valdés for TC3006, with further additions made by Julio Arriaga.

##Numpy

Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays.

To use Numpy, we first need to import the `numpy` package:

In [2]:
import numpy as np

###Arrays

A NumPy array (`ndarray`) is a grid of values, all of the same type (`dtype`), and is indexed by a tuple of nonnegative integers, by booleans, by another array, or by integers. The number of dimensions (usually called `axes`) is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

While a Python list can contain different data types within a single list, all of the elements in a NumPy array should be homogeneous. The mathematical operations that are meant to be performed on arrays would be extremely inefficient if the arrays weren’t homogeneous. NumPy arrays are thus faster and more compact than Python lists. NumPy uses much less memory to store data and it provides a mechanism of specifying the data types. This allows the code to be optimized even further.

We can initialize numpy arrays from nested Python lists, and access elements using square brackets.

Single element indexing works exactly like that for other standard Python sequences. It is 0-based, and accepts negative indices for indexing from the end of the array.

In [2]:
a = np.array([1, 2, 3])  # Create a rank 1 array, also known as a vector
print(type(a), a.shape, a[0], a[1], a[2])
a[0] = 5                 # Change an element of the array
print(a)
print(a[-1])             # Access last element

<class 'numpy.ndarray'> (3,) 1 2 3
[5 2 3]
3


In [ ]:
b = np.array([[1,2,3],[4,5,6]])   # Create a rank 2 array, also known as a matrix
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(b.shape)
print(b[0, 0], b[0, 1], b[1, 0])

(2, 3)
1 2 4


Note that it is not necessary to separate each dimension's index into its own set of square brackets.



In [ ]:
c = np.array([[[1, 2, 3],[4,5,6]],[[7,8,9],[10,11,12]]])  # Create a rank 3 array, also known as a tensor
print(c)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
print(c.shape)
print(c[0])
print(c[0, 0])
print(c[0, 0, 0])

(2, 2, 3)
[[1 2 3]
 [4 5 6]]
[1 2 3]
1


Note also that if one indexes a multidimensional array with fewer indices than dimensions, one gets a subdimensional array.


Finally, note that when you print an array, NumPy displays it in a similar way to nested lists, but with the following layout:

*   The last axis is printed from left to right,
*   The second-to-last is printed from top to bottom,
*   The rest are also printed from top to bottom, with each slice separated from the next by an empty line.

One-dimensional arrays are then printed as rows, bidimensionals as matrices and tridimensionals as lists of matrices.

In addition to `ndarray.shape`, we can also check the number of axes and total number of elements of an array.

In [ ]:
print(c.ndim)
print(c.size)

3
12


Numpy also provides many functions to create arrays:

In [ ]:
a = np.zeros((2,2))  # Create an array of all zeros
print(a)

[[0. 0.]
 [0. 0.]]


In [ ]:
b = np.ones((1,2))   # Create an array of all ones
print(b)

[[1. 1.]]


In [ ]:
c = np.full((2,2), 7) # Create a constant array
print(c)

[[7 7]
 [7 7]]


In [ ]:
d = np.eye(2)        # Create a 2x2 identity matrix
print(d)

[[1. 0.]
 [0. 1.]]


In [ ]:
e = np.random.random((2,2)) # Create an array filled with random values
print(e)

[[0.93123773 0.53063444]
 [0.04912567 0.0496557 ]]


In [ ]:
f = np.empty((2,2))   # Create an "empty" array
print(f)

[[0.93123773 0.53063444]
 [0.04912567 0.0496557 ]]


Most array creation functions will default to `np.float64` type, however we can modify this behavior by providing a different `dtype` argument.

In [ ]:
g = np.ones(2, dtype=np.int64)
print(g)

[1 1]


### Practice Arrays
Create a NumPy array of shape (3,5) that goes from 1 to 15, store it in a varible called test and print its shape an content.

In [4]:
# Complete this code as practice
"""
test =
print(test.shape)
print(test)
"""

a = np.arange(1,16).reshape(3,5)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


Now create an 10 number array filled with random numbers and a (2,4) integer matrix filled with zeros, print both their shapes and contents.

In [5]:
# Complete this code as practice
"""
test_zeros =
test_random =
"""
a = np.random.random(10)
print(a)
b = np.zeros((2,4), dtype=np.int64)
print(b)

[0.16699003 0.63821692 0.26077883 0.88093703 0.49781318 0.69699744
 0.61255981 0.9800161  0.48653302 0.26465037]
[[0 0 0 0]
 [0 0 0 0]]


### Array indexing Basic

Numpy offers several ways to index into arrays.

Slicing: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array. The standard rules of sequence slicing apply to basic slicing on a per-dimension basis (including using a step index).

In [9]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print(b)

[[2 3]
 [6 7]]


Note that : means select all indices along this axis.

In [ ]:
print(a[1:,:])

[[ 5  6  7  8]
 [ 9 10 11 12]]


A slice of an array is a view into the same data, so modifying it will modify the original array.

In [ ]:
print(a[0, 1])
b[0, 0] = 77    # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])

2
77


You can also mix integer indexing with slice indexing. However, doing so will yield an array of lower rank than the original array:

In [ ]:
# Create the following rank 2 array with shape (3, 4)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Two ways of accessing the data in the middle row of the array.
Mixing integer indexing with slices yields an array of lower rank,
while using only slices yields an array of the same rank as the
original array:

In [ ]:
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
row_r3 = a[[1], :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)
print(row_r3, row_r3.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[[5 6 7 8]] (1, 4)


In [ ]:
# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print()
print(col_r2, col_r2.shape)

[ 2  6 10] (3,)

[[ 2]
 [ 6]
 [10]] (3, 1)


If the number of objects in the selection tuple is less than the number of axes, then `:` is assumed for any subsequent dimensions. For example:

In [ ]:
x = np.array([[[1],[2],[3]], [[4],[5],[6]]])
print(x)
print(x.shape)
print()
print(x[1:2])

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]
(2, 3, 1)

[[[4]
  [5]
  [6]]]


Ellipsis can be used to expand to the number of `:` objects needed for the selection tuple to index all dimensions. In most cases, this means that the length of the expanded selection tuple is `x.ndim`. There may only be a single ellipsis present.

In [ ]:
print(x[...,0])   # Same as x[:, :, 0]

[[1 2 3]
 [4 5 6]]


### Practice Array Indexing Basic
Using slicing, get the last 3 numbers of row 2 from array `a`, and store it on `test`.
Then get the first column and store it on `test_col`, without lowering the rank.

In [11]:
# Complete this code as practice

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

test = a[2,-3:]
print(test)

test_col = a[:,0:1]
print(test_col)



[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[10 11 12]
[[1]
 [5]
 [9]]


### Array Indexing Advanced
Integer array indexing: Integer array indexing allows selection of arbitrary items in the array based on their N-dimensional index. Each integer array represents a number of indices into that dimension.

Negative values are permitted in the index arrays and work as they do with single indices or slices:

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a)
print(a[[0, 2, 5, -3]])

[1 2 3 4 5 6]
[1 3 6 4]


When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array. In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array. Here is an example:

In [ ]:
a = np.array([[1,2], [3, 4], [5, 6]])
print(a)
print(a.shape)

# An example of integer array indexing.
# The returned array will have shape (3,)
print(a[[0, 1, 2], [0, 1, 0]])
print(a[[0, 1, 2], [0, 1, 0]].shape)

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))
print(np.array([a[0, 0], a[1, 1], a[2, 0]]).shape)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)
[1 4 5]
(3,)
[1 4 5]
(3,)


In [ ]:
# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]])

# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))

[2 2]
[2 2]


One useful trick with integer array indexing is selecting or mutating one element from each row of a matrix:

In [ ]:
# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


  to do this you can use the [`np.arange()`](https://numpy.org/doc/stable/reference/generated/numpy.arange.html?highlight=arange#numpy.arange) function. This function is similar to Python's `range()` function, but returning a `ndarray` instead.
  
For instance, `np.arange(4)` creates an `ndarray [0 1 2 3]`, so when substituted in the line `a[np.arange(), b])` will look like this `a([[0, 1, 2, 3], [0, 2, 0, 1]])`.


In [ ]:
# Create an array of indices
b = np.array([0, 2, 0, 1])

# Select one element from each row of a using the indices in b
print(a[np.arange(4), b])  # Prints "[ 1  6  7 11]"

[ 1  6  7 11]


In [ ]:
# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10
print(a)

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


The broadcasting mechanism permits index arrays to be combined with scalars for other indices. The effect is that the scalar value is used for all the corresponding values of the index arrays:

In [ ]:
c = np.arange(35).reshape(5, 7)
print(c)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]


In [ ]:
print(c[[0, 2, 4], 1])

[ 1 15 29]


It is also possible to only partially index an array with index arrays.

In [ ]:
print(c[[0, 2, 4]])

[[ 0  1  2  3  4  5  6]
 [14 15 16 17 18 19 20]
 [28 29 30 31 32 33 34]]


Boolean array indexing: Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition. Here is an example:

In [ ]:
a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)  # Find the elements of a that are bigger than 2;
                    # this returns a numpy array of Booleans of the same
                    # shape as a, where each slot of bool_idx tells
                    # whether that element of a is > 2.

print(bool_idx)

[[False False]
 [ True  True]
 [ True  True]]


In [ ]:
# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])

# We can do all of the above in a single concise statement:
print(a[a > 2])

[3 4 5 6]
[3 4 5 6]


In [ ]:
# You can select elements that satisfy two conditions using the & and | operators:
print(a[(a > 2) & (a < 5)])

[3 4]


You can use `np.nonzero()` to print the indices of elements that satisfy a given condition:

In [ ]:
b = np.nonzero((a > 1) & (a < 6))
print(b)
print(a[b])

(array([0, 1, 1, 2]), array([1, 0, 1, 0]))
[2 3 4 5]


In this example, a tuple of arrays was returned: one for each dimension. The first array represents the row indices where these values are found, and the second array represents the column indices where the values are found. You can also use this result to access the values directly.

A common use case for this is filtering for desired element values. For example, one may wish to select all entries from an array which are not NaN:

In [ ]:
x = np.array([[1., 2.], [np.nan, 3.], [np.nan, np.nan]])
print(x)
print(x[~np.isnan(x)])

[[ 1.  2.]
 [nan  3.]
 [nan nan]]
[1. 2. 3.]


Or transforming certain values:

In [ ]:
x = np.array([1., -1., -2., 3])
x[x < 0] += 20    # Adding 20 to all negative values
print(x)

[ 1. 19. 18.  3.]


For brevity we have left out a lot of details about numpy array indexing; if you want to know more you should read the documentation.

### Practice Array Indexing Advanced

From matrix `a` create a new array `test` that stores elements 4, 7 and 12, using ingeter array indexing. The resulting array should be shape

     (3,)
  
and the array should print

      [4, 7, 12]

From matrix `a` mutate elements 1, 5, and 10 by multiplying them by 100 and print them. The resulting matrx should be:

      a = np.array([[100,2,3,4], [500,6,7,8], [9,1000,11,12]])

In [18]:
# Complete this code as practice

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

test = a[np.arange(3), [-1,-2,-1]]
print(test)



[ 4  7 12]


### Reshaping Arrays

Using `ndarray.reshape()` will give a new shape to an array without changing the data. Just remember that when we use the reshape method, the array we want to produce needs to have the same number of elements as the original array. If we start with an array with 12 elements, we’ll need to make sure that our new array also has a total of 12 elements.

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [ ]:
b = a.reshape(3,2)
print(b)

[[1 2]
 [3 4]
 [5 6]]


We can use `np.newaxis` and `np.expand_dims` to increase the dimensions of an existing array.

Using `np.newaxis` will increase the dimensions of an array by one dimension when used once. This means that a 1D array will become a 2D array, a 2D array will become a 3D array, and so on.

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a)
print(a.shape)

[1 2 3 4 5 6]
(6,)


In [ ]:
a2 = a[np.newaxis, :]
print(a2)
print(a2.shape)

[[1 2 3 4 5 6]]
(1, 6)


In [ ]:
a3 = a[:, np.newaxis]
print(a3)
print(a3.shape)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)


We can also expand an array by inserting a new axis at a specified position with `np.expand_dims`.

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [ ]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [ ]:
b = np.expand_dims(a, axis=0)
b.shape

(1, 6)

### Practice Array Reshaping

From matrix `a` create a new tensor `test` with shape (3,2,2,1).

In [20]:
# Complete this code as practice
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
test = a.reshape(3,2,2,1)
print(test)


[[[[ 1]
   [ 2]]

  [[ 3]
   [ 4]]]


 [[[ 5]
   [ 6]]

  [[ 7]
   [ 8]]]


 [[[ 9]
   [10]]

  [[11]
   [12]]]]


###Datatypes

Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays. Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype. Here is an example:

In [ ]:
x = np.array([1, 2])  # Let numpy choose the datatype
y = np.array([1.0, 2.0])  # Let numpy choose the datatype
z = np.array([1, 2], dtype=np.int64)  # Force a particular datatype

print(x.dtype, y.dtype, z.dtype)

int64 float64 int64


You can read all about numpy datatypes in the [documentation](http://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html).

###Array math

Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:

In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [ ]:
# Elementwise difference; both produce the array
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [ ]:
# Elementwise product; both produce the array
print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [ ]:
# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [ ]:
# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


Note that unlike MATLAB, `*` is elementwise multiplication, not matrix multiplication. We instead use the dot function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. dot is available both as a function in the numpy module and as an instance method of array objects:

In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

219
219


You can also use the `@` operator which is equivalent to numpy's `dot` operator.

In [ ]:
print(v @ w)

219


In [ ]:
# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))
print(x @ v)

[29 67]
[29 67]
[29 67]


In [ ]:
# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))
print(x @ y)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


Numpy provides many useful functions for performing computations on arrays; one of the most useful is `sum`:

In [ ]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

10
[4 6]
[3 7]


You can find the full list of mathematical functions provided by numpy in the [documentation](http://docs.scipy.org/doc/numpy/reference/routines.math.html).

Apart from computing mathematical functions using arrays, we frequently need to reshape or otherwise manipulate data in arrays. The simplest example of this type of operation is transposing a matrix; to transpose a matrix, simply use the T attribute of an array object:

In [ ]:
print(x)
print("transpose\n", x.T)

[[1 2]
 [3 4]]
transpose
 [[1 3]
 [2 4]]


In [ ]:
v = np.array([[1,2,3]])
print(v )
print("transpose\n", v.T)

[[1 2 3]]
transpose
 [[1]
 [2]
 [3]]


### Practice Array Math
For the the following matrix

    a = np.array([[1,2,3], [4,5,6], [7,8,9]])

    b = np.array([[11,12,13], [14,15,16], [17,18,19]])

Add the matrix formed by the first and second rows of a with a matrix formed by the second and third rows of b, the result should be

    [[15, 17, 19],
     [21, 23, 25]]

Multiply the first row matrix a by the transpose of the first column of matrix b. If you use integer index you should get:

    [11 28 51]

if you use slices and transpose you should get:

    [[11 28 51]]

Get the dot product of the transpose of matrix a with a matrix composed of the rows of b in reverse order, the result should be:

    [[150 162 174]
    [192 207 222]
    [234 252 270]]

In [11]:
# Complete this code as practice


a = np.array([[1,2,3], [4,5,6], [7,8,9]])
b = np.array([[11,12,13], [14,15,16], [17,18,19]])


mat_add = np.add(a[0:2], b[1:3])

mat_mult = a[0,:] * b[:,0].T

mat_dot = np.dot((a.T), b[::-1])

print(mat_add, "\n")
print(mat_mult, "\n")
print(mat_dot, "\n")


[[15 17 19]
 [21 23 25]] 

[11 28 51] 

[[150 162 174]
 [192 207 222]
 [234 252 270]] 



### Broadcasting

Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

For example, suppose that we want to add a constant vector to each row of a matrix. We could do it like this:

In [ ]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


This works; however when the matrix `x` is very large, computing an explicit loop in Python could be slow. Note that adding the vector v to each row of the matrix `x` is equivalent to forming a matrix `vv` by stacking multiple copies of `v` vertically, then performing elementwise summation of `x` and `vv`. We could implement this approach like this:

In [ ]:
vv = np.tile(v, (4, 1))  # Stack 4 copies of v on top of each other
print(vv)                # Prints "[[1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]]"

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


In [ ]:
y = x + vv  # Add x and vv elementwise
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Numpy broadcasting allows us to perform this computation without actually creating multiple copies of v. Consider this version, using broadcasting:

In [ ]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


The line `y = x + v` works even though `x` has shape `(4, 3)` and `v` has shape `(3,)` due to broadcasting; this line works as if v actually had shape `(4, 3)`, where each row was a copy of `v`, and the sum was performed elementwise.

Broadcasting two arrays together follows these rules:

1. If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.
2. The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.
3. The arrays can be broadcast together if they are compatible in all dimensions.
4. After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.
5. In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension

Example: if you have a `256x256x3` array of RGB values, and you want to scale each color in the image by a different value, you can multiply the image by a one-dimensional array with 3 values. Lining up the sizes of the trailing axes of these arrays according to the broadcast rules, shows that they are compatible:

```
Image  (3d array): 256 x 256 x 3
Scale  (1d array):             3
Result (3d array): 256 x 256 x 3
```

When either of the dimensions compared is one, the other is used. In other words, dimensions with size 1 are stretched or "copied" to match the other.

If this explanation does not make sense, try reading the explanation from the [documentation](http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html) or this [explanation](http://wiki.scipy.org/EricsBroadcastingDoc).

Functions that support broadcasting are known as universal functions. You can find the list of all universal functions in the [documentation](http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs).

Here are some applications of broadcasting:

In [ ]:
# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:

print(np.reshape(v, (3, 1)) * w)

[[ 4  5]
 [ 8 10]
 [12 15]]


In [ ]:
# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:

print(x + v)

[[2 4 6]
 [5 7 9]]


In [ ]:
# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:

print((x.T + w).T)

[[ 5  6  7]
 [ 9 10 11]]


In [ ]:
# Another solution is to reshape w to be a row vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print(x + np.reshape(w, (2, 1)))

[[ 5  6  7]
 [ 9 10 11]]


In [ ]:
# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
print(x * 2)

[[ 2  4  6]
 [ 8 10 12]]


Broadcasting typically makes your code more concise and faster, so you should strive to use it where possible.

This brief overview has touched on many of the important things that you need to know about numpy, but is far from complete. Check out the [numpy reference](http://docs.scipy.org/doc/numpy/reference/) to find out much more about numpy.